[package]
name = "web_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.23", features = ["auto-initialize"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.23.1"
serde_json = "1.0"
